fs = 1e6; 
N = 200; 

t = (0:N-1)/fs;


f1 = 5e3;     % 5kHz
f2 = 20e3;    % 20kHz


sig = 0.3*sin(2*pi*f1*t) + 0.3*sin(2*pi*f2*t) + 0.3*sin(2*pi*f3*t);

% 归一化到16位有符号数 [-32768, 32767]
sig = sig / max(abs(sig));  % 先归一化幅度至[-1,1]
sig_int16 = int16(sig * 32767);

% 画图
figure; plot(t(1:200), double(sig_int16(1:200))/32767);
title('叠加正弦波波形（前200点）');
xlabel('时间(s)');
ylabel('归一化幅值');


% 生成 COE 文件
fileID = fopen('sine_test.coe','w');
fprintf(fileID, '; FIR Filter Coefficients generated by MATLAB\n');
fprintf(fileID, 'memory_initialization_radix=16;\n');       % 16进制基数
fprintf(fileID, 'memory_initialization_vector=\n');

for k = 1:N
    val = typecast(sig_int16(k), 'uint16'); % 转无符号，方便格式化
    if k ~= N
        fprintf(fileID, '%04X,\n', val);
    else
        fprintf(fileID, '%04X;\n', val); % 最后一个用分号结束
    end
end

fclose(fileID);
